### ISSUE TITLE
Translator install

### ISSUE THREAD

**Issue by fbennett** [Juris-M/zotero-odf-scan-plugin#1]
Apparently the translator is not being installed with the plugin.

**Comment by rmzelle** [comment]
See

https://forums.zotero.org/discussion/comment/265421/#Comment_265421
https://forums.zotero.org/discussion/63238/scannable-cite-is-not-reflected-in-export-in-zotero-preferences
https://forums.zotero.org/discussion/comment/265097/#Comment_265097

**Comment by fbennett** [comment]
Oh. The new packaging script isn't including the translator when it builds the plugin. Fix on its way ...

**Comment by fbennett** [comment]
The iterator in the shell script was tripping up on the space in the filename. Using null delimiters on the list of filenames fixes it ...

**Comment by fbennett** [comment]
Should be working now, in tag v1.0.33. Sorry about this one.

**Comment by rmzelle** [comment]
Great, thanks!

(I ran into this as I spent some time sprucing up the documentation page, see https://github.com/Zotero-ODF-Scan/zotero-odf-scan/pull/21)
