### ISSUE TITLE
Switch between: zu:1234566 style and hyperlink style: zotero://select/items/0_AXB58PXJ

### ISSUE THREAD

**Issue by paultroop** [Juris-M/zotero-odf-scan-plugin#16]
I've had ODF scan set up to work as a hyperlink (zotero://select/items/0_AXB58PXJ) since Frank first helped me to set it up. I've just reinstalled Zotero and ODF scan, and it has reverted back to the zu:123456 etc style. Can somebody remind me how to switch between the styles please?

**Comment by adam3smith** [comment]
You'll want to set the hidden prefence `extensions.zotero.translators.ODFScan.useZoteroSelect` to true (hidden preferences are accessible from about:config in the Advanced tab of the Zotero preferences)

**Comment by paultroop** [comment]
Yes, that's sorted it! Fantastic. Thank you very much for your prompt and helpful response.

Is it worth adding this information on the main page about the plug-in? It's a pretty useful function.

**Comment by adam3smith** [comment]
It's listed here under Customizing... https://zotero-odf-scan.github.io/zotero-odf-scan/

**Comment by paultroop** [comment]
Oops, sorry. Well done on including this.
