### ISSUE TITLE
A Zotero 5 version

### ISSUE THREAD

**Issue by gagarine** [Juris-M/zotero-odf-scan-plugin#2]
I was unable to install the extension on Zotero 5.

**Comment by yetiinabox** [comment]
Now that Zotero 5 is public, we would be very very grateful for a Z5 compatible version of this wonderful plugin!

—WBTD.

**Comment by vtcarlino** [comment]
I cannot agree more: we *need* a Z5 compatible version of this plugin! It's at the core of my workflow.

**Comment by gagarine** [comment]
Now I think this is not the right approach so I will not personally spend time to port this plugin. I really think the citation system should be document type and editor agnostic like http://support.mekentosj.com/kb/cite-write-your-manuscripts-and-essays-with-citations/magic-citations-on-papers-3-for-mac

this is also linked with #4

**Comment by fbennett** [comment]
I should have time to look at Z5 compatibility later this week. It's running in Juris-M 5.0, which is based on Z5, so any issues should be minor.

**Comment by atanasj** [comment]
Looking forward to the Z5 version!!

**Comment by debritto** [comment]
Please, do you know when Z5 compatibility will be available?
Best regards

**Comment by fbennett** [comment]
Very soon!

**Comment by debritto** [comment]
Something new?

**Comment by debritto** [comment]
?

**Comment by atanasj** [comment]
Any progress??

**Comment by debritto** [comment]
Progress?

**Comment by debritto** [comment]
Plz... It's important!

**Comment by vtcarlino** [comment]
@chriseana Apparently, Scannable Cite works in Z5 but you have to install it manually : https://twitter.com/adam42smith/status/922904470995992576 

Haven't tried it, looking for your feedback!

**Comment by adam3smith** [comment]
yeah, the add-on works in Zotero 5. Only scannable cite install is broken.
