### ISSUE TITLE
Conversion Corrupts ODF File

### ISSUE THREAD

**Issue by paultroop** [Juris-M/zotero-odf-scan-plugin#21]
I get the following error report on conversion:
'Read Error.
Format error discovered in the file in sub-document content.xml at 3,0(row,col).'
I'm using:
- LO 6.0.6.2 and later 6.0.7 (same problem)
- OX10.11.6
- Z 5.0.58 with LO add-ins.
- Add-on 2.0.41

**Comment by paultroop** [comment]
It is possibly due to the fact that Scrivener converts some of the hyperlink style references that I use to real hyperlinks. Stripping these 'live' links out by converting to txt and back seems to have solved the problem. Many thanks to Sebastian.

**Comment by adam3smith** [comment]
Thanks for reporting back. I think it's pretty certain that's the issue. Given that, I'd consider going back to using the zu: style markers instead of zotero://select, but up to you.

**Comment by paultroop** [comment]
No worries. I find the zotero:// hyperlink function is really useful and saves a lot of time, so I guess I'll just be more careful that autotext doesn't convert to 'live' hyperlinks.
