### ISSUE TITLE
Error with locators etc.

### ISSUE THREAD

**Issue by ghost** [Juris-M/zotero-odf-scan-plugin#22]
After scanning the ODF file, additional information such as locators, pre- and suffixes to the citations get lost. Is this a general problem? As far as I remember, it worked fine with the old Zotero & plugin.

**Comment by adam3smith** [comment]
Have you selected a citation style? Prefix/suffix and locators do no show after scanning (and never have), only once you have actually selected a citation style in LibreOffice under Document Preferences.

**Comment by ghost** [comment]
Thanks for your reply! I have, so it seems to be a problem of the citation style and not the plugin.
