### ISSUE TITLE
How to build the plugin?

### ISSUE THREAD

**Issue by fbennett** [Juris-M/zotero-odf-scan-plugin#25]
It's great to see the cleanup work by @adam3smith and @retorquere in this space - spoken with humble apologies for taking time off and looking the other way.

It would like to bundle the plugin for a fresh release of Juris-M. From the commit logs, it looks like the entry point is `build.py`? I tried running that, and got this error:
```
  File "./build.py", line 27
    self.xpi = f'zotero-odf-scan-v{self.version}.xpi'
                                                    ^
SyntaxError: invalid syntax
```
How should I go about building the XPI?

**Comment by retorquere** [comment]
Apologies -- are you kidding? Considering your contributions to Zotero and citeproc? Pshaw.

Are you maybe running it with `python build.py`? Currently build.py requires python3, and your default python could well be python2. If so desired I can change the script to py2, but py3 is the future, and the code is substantially more readable IMO.

**Comment by fbennett** [comment]
The error is with python 3.5.2. I guess it needs an update?

**Comment by retorquere** [comment]
Yeah sorry, I use PEP 498, which is 3.6+. If this is burdensome, I can change this.

**Comment by fbennett** [comment]
No problem. I think I've gotten the old homebrew build working - and in fact I didn't need to build, come to think of it, since the plugins are just added to the client builder as git submodules. I just needed to stick a version string into `install.rdf` to avoid a Moz error.

**Comment by fbennett** [comment]
Done, and it runs. Very nice touch with the UI, too!
