### ISSUE TITLE
2.0.35 doesn't update to 2.0.41

### ISSUE THREAD

**Issue by retorquere** [Juris-M/zotero-odf-scan-plugin#26]
I don't know why this happens though. I've downloaded 2.0.35 and looked into the `install.rdf`, which has an `updateURL` pointing to https://juris-m.github.io/zotero-odf-scan-plugin/update.rdf, which exists and looks OK to me. But I've installed 2.0.35 and it just says there's no update when I tell Zotero to look for updates.

**Comment by retorquere** [comment]
Wait -- the update.rdf only has an entry for firefox.

**Comment by retorquere** [comment]
See https://github.com/Juris-M/zotero-odf-scan-plugin/pull/27

**Comment by fbennett** [comment]
Aha. Thanks for chasing and nailing this.

**Comment by retorquere** [comment]
The plugin doesn't need to be rebuilt BTW, the pull request will update the `update.rdf` on the site and that will fix it.

**Comment by retorquere** [comment]
I have a stake in this PR being merged in that BBT breaks when 2.0.35 is installed, and people must manually update from 2.0.35 to 2.0.41 without this.

**Comment by fbennett** [comment]
Sorry about that, I've merged the pull request. I see node and python scripts ... if anything is needed at this end to wake it up, just let me know.

**Comment by retorquere** [comment]
Nope, the PR just merges a new `update.rdf` that enables updates. The python script will generate a new one for new releases, but that would just be committed with the rest of the stuff it generates.

**Comment by fbennett** [comment]
Sounds good. Could you drop a short description of the system requirements and upgrade steps into a README? I still get a syntax error on `build.py`, and there is a `package.json` but I'm not sure how `node` fits in.
