### ISSUE TITLE
Error running `python build.py`

### ISSUE THREAD

**Issue by jamesray1** [Juris-M/zotero-odf-scan-plugin#30]
This was with cloning the latest master.

```
 18:56:36  jr@fm  ~/zotero-odf-scan-plugin  ⬡ v8.16.0   master ✔  17s 
$ python build.py
Traceback (most recent call last):
  File "build.py", line 8, in <module>
    from lxml import etree
ModuleNotFoundError: No module named 'lxml'

 18:56:42  ✘  jr@fm  ~/zotero-odf-scan-plugin  ⬡ v8.16.0   master ✔ 
$ python --version
Python 3.7.3
```

**Comment by jamesray1** [comment]
Before this, I also didn't read the installation instructions at https://zotero-odf-scan.github.io/zotero-odf-scan/, and just went straight to the download add-on button, and clicking on the xpi file gave an error from Firefox.

Maybe also repeat the installation instructions in the release to avoid this problem.

https://i.imgur.com/GN8LoFL.png

https://i.imgur.com/pbJ1O1v.png

**Comment by fbennett** [comment]
The Python build chain wasn't written by me - maybe @retorquere and @adam3smith can help with docs?

**Comment by retorquere** [comment]
Updated README in https://github.com/Juris-M/zotero-odf-scan-plugin/pull/31

**Comment by fbennett** [comment]
Merged. Thanks!

**Comment by adam3smith** [comment]
(The Firefox error is unavoidable -- that happens when you open Zotero add-ons in Firefox)

**Comment by retorquere** [comment]
Right-click and save rather than left-click does the job.
