### ISSUE TITLE
Feature or doc request: a simpler syntax to avoid confusing non geek collaborators

### ISSUE THREAD

**Issue by bokov** [Juris-M/zotero-odf-scan-plugin#38]
Use case: working with people used to seamless interfaces on a platform that doesn't natively support Zotero (in my case OneDrive and Office 365 Online).

Furthermore, let's assume we have a shared citations file with manually created unique human-readable keys, e.g. `{smith03}`.

# Most ambitious version of this feature request
It would make things very simple for everyone if I could just tell them: "use our agreed-upon key to represent each citation and at the end I'll convert it all to beautifully formatted references without you having to worry about it".

**Could you please consider making ODF Scan's choice of key configurable-- e.g. manually assigned keys or the ones generated by BetterBibTex**, so they really could literally type in `{smith03}` (or, dare I ask, even square brackets?). This is the most intuitive way for most people I've ever worked with to express barebones citation placeholders (i.e. without special cases like prefixes, suffixes, locators, etc).

# Less ambitious version of this feature request
We could live with citations that look like `{smith03|0_AXVB9R}` with the first section optional. Though people will definitely sometimes get them mixed up if they're typing them in by hand, and it's needless redundancy (if the user did their job of insuring unique human readable keys, and if they didn't, it's their own fault for opting for human-readable keys).

But what we're looking at right now is `{ | Smith, A Title (2003) | | |zg:2473041:AL3K25SG}`. That's a chunk of text too large to ask people to type by hand and it is more likely to be clobbered by cut-and-paste. The `|` characters are mandatory even if you want to use default values for those sections and people typing repetitive pipe characters will lose count and corrupt the import.

**So, if it's not too difficult, would you consider permitting omitted sections? I.e. if there is only one section, assume it's the key (and fill the item description section with a copy of the key); if there are two, assume they are item description and key; if there are three, assume they're item description, locator, and key; if there are four then prefix, item description, locator, and key; if there are all five then interpret them as all five. If a user needs to use sections in a manner that departs from this order of precedence then they can still use empty pipe-delimited sections to unambiguously communicate their intent.**

# Least ambitious version of this feature request

I have a workaround: I will tell my collaborators to go ahead and cite `{smith03}`. When it's time to populate the reference I use the following search-replace regexp pattern (having downloaded the document and opened it in LibreOffice):

Search: `\{([a-z0-9]+)\}`
Replace: `{|$1|||$1}`

Every instance of `{smith03}` gets replaced with `{|smith03|||smith03}` (and `{jones04}` gets replaced with `{|jones04|||jones04}`). I save the document in ODF format, run ODF scan on it, and open it in LibreOffice Write. I click the "Refresh" Zotero button, select a citation format, and get prompted with...
![Screenshot from 2020-04-24 17-53-15](https://user-images.githubusercontent.com/5765730/80262913-8847c080-8654-11ea-9bed-18c4661decad.png)

I click `Yes` and manually select the correct reference... and continue doing so for every reference in the document.

**If the above two versions of this feature request are too difficult, could you please consider retaining each invalid key and the substitute item the user selected for it, so that the user only gets asked to select a replacement value once per Zotero database entry?**

That way the user-hostile/software-convenient format remains as is but at least the manual replacement workflow isn't even more repetitive than it needs to be.

Thanks. I know it's easier said than done, but I'm hoping one of the above is something you can do to help people stuck with Office365 Online (e.g. Linux users or geographically distributed collaborations that need to be able to work on documents synchronously).

**Comment by bokov** [comment]
Just realized that option 3 (least ambitious) is probably Zotero's behavior, not this plugin's. So I guess only the first two ideas are actionable here...

**Comment by retorquere** [comment]
I think if you open the Zotero document preferences instead of refresh, it will refresh them all without prompting. After that, refresh should work.

**Comment by adam3smith** [comment]
Closing this as won't-fix/won't implement. Zotero will get proper citekeys and then hopefully build something simpler, but we're not going to try to implement it in this add-on (which we can hopefully sunset once a simpler native version arrives)
