### ISSUE TITLE
Unable to install Zotero ODF Scan plugin on Firefox 68.10.0esr (64-bit)

### ISSUE THREAD

**Issue by kjambunathan** [Juris-M/zotero-odf-scan-plugin#40]
I am running

~$ dpkg -l | grep firefox
ii firefox-esr 68.10.0esr-1 amd64 Mozilla Firefox web browser - Extended Support Release (ESR)

~$ uname -a
Linux debian 5.7.0-1-amd64 #1 SMP Debian 5.7.6-1 (2020-06-24) x86_64 GNU/Linux

When I click on this link https://github.com/Juris-M/zotero-odf-scan-plugin/releases/download/v2.0.43/zotero-odf-scan-v2.0.43.xpi (from https://github.com/Juris-M/zotero-odf-scan-plugin/releases/tag/v2.0.43), firefox refuses to install the file saying it is corrupt.

The behaviour is the same when download the `xpi` file, and open it in Firefox.

I am not sure if this issue requires a Report ID. I will be happy to create one if needed.

**Comment by kjambunathan** [comment]
This  is what the firefox reports

![Screenshot from 2020-07-21 22-07-42](https://user-images.githubusercontent.com/19869864/88081931-b7f85d00-cb9e-11ea-963a-62df5fe06912.png)

**Comment by dstillman** [comment]
Answered here: https://forums.zotero.org/discussion/comment/360886/#Comment_360886

This should be closed.

**Comment by kjambunathan** [comment]
> Answered here: https://forums.zotero.org/discussion/comment/360886/#Comment_360886
> 
> This should be closed.

Done.
