### ISSUE TITLE
`Tools->ODF Scan` in a command line interface

### ISSUE THREAD

**Issue by kjambunathan** [Juris-M/zotero-odf-scan-plugin#42]
Not a bug, but a feature request / developer query

## `Tools->ODF Scan` in a command line interface

I am the owner of OpenDocument export engine of Emacs Orgmode.  See https://github.com/kjambunathan/org-mode-ox-odt.

 I would like a command line tool to convert a `scannable cite` odt output by `better bibtex` (cf. https://github.com/retorquere/zotero-better-bibtex/issues?q=is%3Aissue+author%3Akjambunathan ) to the command line equivalent of `Tools->ODF Scan`.

**Comment by retorquere** [comment]
You can probably put this together using the [debug bridge](https://github.com/retorquere/zotero-better-bibtex/tree/master/test/fixtures/debug-bridge).

**Comment by adam3smith** [comment]
We won't fix beyond the above suggestion, though, sorry.
