### ISSUE TITLE
Update `filePicker` path for Zotero 6

### ISSUE THREAD

**Issue by dstillman** [Juris-M/zotero-odf-scan-plugin#46]
https://forums.zotero.org/discussion/91733/odf-scan-plug-in-broken-report-id-1639679225

The `require()` for the file picker needs to be [updated](https://github.com/zotero/zotero/commit/af597d943bd1128e741d530ef4b1d0ebaf8d3b25#) for current betas.

I haven't tested, but you can likely fix this by adding a `try`/`catch` here:

https://github.com/Juris-M/zotero-odf-scan-plugin/blob/26b07a326fd67dd74c275a3802b63a93d079935a/chrome/content/rtfScan.js#L30

Try this:

```javascript
try {
    // Zotero 6
    var FilePicker = require('zotero/modules/filePicker').default;
}
catch (e) {
    // Zotero 5
    var FilePicker = require('zotero/filePicker').default;
}
```

**Comment by dstillman** [comment]
Temporary shim added in https://github.com/zotero/zotero/commit/4cfa230508e05a241cfeda05f68d137b8b8d3031

**Comment by adam3smith** [comment]
Updated as suggested above
