### ISSUE TITLE
Converting Scannable Cites to Bibtex?

### ISSUE THREAD

**Issue by paultroop** [Juris-M/zotero-odf-scan-plugin#50]
Is there any (theoretical) way of converting scannable cites to a Bibtex format?

I'm using the { | Smith, 2021 | | |zotero://select/items/0_ABCDEFGH}

All my note references are in scannable cites, but I'm considering switching to Latex for a big writing project.

I can imagine that even if they could be converted, it might be tricky to extract the relevant items from Zotero to create the accompanying biographic database.

Apologies if this is totally out of the question, I'm afraid I do not have the technical knowledge to understand if this could be feasible.

**Comment by retorquere** [comment]
You can convert the scannable cites to an ODF document with live citations, and then use a [specialized style](https://retorque.re/zotero-better-bibtex/citing/migrating/) to get them replaced with citekeys.

**Comment by wenbopeng** [comment]
I hope conversely, is there a way to convert [@citekey] in plain text(markdown rtf odt or docx)  into { | Smith, 2021 | | |zotero://select/items/0_ABCDEFGH}?

**Comment by adam3smith** [comment]
Not easily, no. I think there is a way to use a LUA filter and BetterBibTeX to create a .docx or .odt file with live Zotero citations. You can turn that into a .odt file if applicable and then run scan to markers in the add-on.

**Comment by retorquere** [comment]
For the first part: https://retorque.re/zotero-better-bibtex/exporting/pandoc/#from-markdown-to-zotero-live-citations

**Comment by wenbopeng** [comment]
> For the first part: https://retorque.re/zotero-better-bibtex/exporting/pandoc/#from-markdown-to-zotero-live-citations

Awesome! This is the perfect solution I was looking for, thank you retorquere!

**Comment by wenbopeng** [comment]
> For the first part: https://retorque.re/zotero-better-bibtex/exporting/pandoc/#from-markdown-to-zotero-live-citations

Another issue: 
Is there a way to implement the author as sentence component like Pandoc-citeproc? eg. `[@citekey] -> (author,2019)` and `@citekey -> author(2019) `

Thanks again for your answer!

**Comment by retorquere** [comment]
Sort of. From that link:

> author-in-text: false # when true, enabled fake author-name-only cites by replacing it with the text of the last names of the authors

which, when set to `true`, will write the names of the creators into the document at time of conversion, just before the omit-author citation field. The creator names won't update after that if you change the item in Zotero. Zotero (unfortunately) does not support author-in-text.
