### ISSUE TITLE
Wrong URI all of a sudden

### ISSUE THREAD

**Issue by GabrielleduVent** [Juris-M/zotero-odf-scan-plugin#54]
I previously compiled bibliography using LibreOffice and ODF scan without an issue. Updating bibliography and changing styles worked without any hitch. However, today I was compiling a new version of the document, and suddenly EVERY SINGLE citation comes up with "The highlighted citation no longer exists in your Zotero database" message. 

The internal identifier has not changed (I have not merged or deleted any item in the Zotero database); upon inspection, it appears that the URI is ALWAYS http://zotero.org/users/local/items/[8 digit identifier]". However, when I check the URI with Zutilo it is supposed to be https://www.zotero.org/users/[7 digit numerical ID]/items/[8 digit identifier]. 

Is there any way for me to batch-change the URIs so that I can update without having to replace 100+ citations?

**Comment by adam3smith** [comment]
Try the beta version under releases

**Comment by jamesylin** [comment]
I had the same issue after updating to 2.0.46 a couple days ago.  Updating to 2.0.47-beta and redoing ODF scan resolved the issue for me.

**Comment by GabrielleduVent** [comment]
Updating to beta resolved it. I assume this might be a common issue.

**Comment by adam3smith** [comment]
Thanks for reporting back & sorry about this. I've just pushed 2.0.47 with the fix. I'm still not sure if I or Zotero broke this.
