### ISSUE TITLE
ODF (to citation) works while ODF (to markers) doesn't work

### ISSUE THREAD

**Issue by Sun-Pengcheng** [Juris-M/zotero-odf-scan-plugin#55]
Hi. I use the plugin (2.0.48) in Zotero (6.0.15) on Windows 11 (21H2, 22000.1042).
ODF (to citation) works well for an ODT file, but RTF file with the same content doesn't seem to work.
The references still appear in the style of "{ | Gupta, et al., 2020 | | |zu:6596034:QKSP3IJH}".
Is there a difference in the formatting required for the two conversion methods?

**Comment by bwiernik** [comment]
Yes, that format is specifically for ODF. The RTF scan uses a simpler but less reliable structure: https://www.zotero.org/support/rtf_scan

If you are already working with this plugin, you should stick with ODF.

**Comment by Sun-Pengcheng** [comment]
I get it. Thanks a lot.

**Comment by Sun-Pengcheng** [comment]
> Yes, that format is specifically for ODF. The RTF scan uses a simpler but less reliable structure: https://www.zotero.org/support/rtf_scan
> 
> If you are already working with this plugin, you should stick with ODF.


I get it. Thanks a lot.
