### ISSUE TITLE
Using the plugin to create odf citations and then opening in Word yields inactive citations?

### ISSUE THREAD

**Issue by jklann** [Juris-M/zotero-odf-scan-plugin#7]
I am doing the following
- Writing my document in Google Docs
- Export to ODF
- Process with ODF Scan plugin
- Open in MS Word

The result are inactive citations that I cannot edit with Zotero. (i.e., the {} block is replaced by author-year with no bibliography and 'set document options' from the Zotero toolbar says 'no citations'). Is that expected behavior?

**Comment by fbennett** [comment]
To refresh the citations after processing with the ODF Scan plugin, open the document with LibreOffice. After refresh, if you need to move the document to Word while preserving live citations, the following steps should work:

1. Switch the document to a non-footnote style (such as Cell or Vancouver).
2. In Zotero or Juris-M preferences, change the references from ReferenceMarks to Bookmarks.
3. Save the document in a Word format (*.doc or *.docx -- I tested just now with *.doc).
4. Open the document in Word.
5. Immediately change the references from Bookmarks to Fields.
6. Continue editing in Word.
