### ISSUE TITLE
Error with new firefox

### ISSUE THREAD

**Issue by littleoopie** [Juris-M/zotero-odf-scan-plugin#8]
I downloaded firefox specifically for this, but it says it isn't compatible with the newest version. 
![screen shot 2018-01-02 at 9 43 42 am](https://user-images.githubusercontent.com/35035312/34487296-c27a066a-efa1-11e7-8acf-0d81ccb2cfde.png)

**Comment by andersjohansson** [comment]
Zotero is not compatible with firefox anymore (due to deep changes in firefox). You should download Zotero 5 standalone, and then right-click the xpi-link and choose "save link as". Then you can install the add-on in Zotero standalone.

> To install a plugin in Zotero, download its .xpi file to your computer. Then, in Zotero, click “Tools → Add-Ons”, then drag the .xpi for the plugin onto the Add-Ons window that opens. 

https://www.zotero.org/support/plugins
